# Generated by Django 2.2.13 on 2021-05-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='cover',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
